### ISSUE TITLE
The Jacobi 

### ISSUE THREAD

**Issue by chengwei0427** [i2Nav-WHU/FF-LINS#1]
Hi, @thlsealight 
Thanks for your nice work!
Is that the derivative of **r** with respect to **R_b_r** ?
![image](https://github.com/i2Nav-WHU/FF-LINS/assets/20199999/83b95544-7df9-43b6-ab4e-a41143687ee9)

**Comment by thlsealight** [comment]
I know what you are thinking, but I think this formula is not correct. Because all the two terms in formula (10) are from $p^{r_i,h}$. I suggest you read the paper and the codes carefully.

**Comment by chengwei0427** [comment]
感谢回复，我就用中文了。
所以，这里求导，是整个等式$p^{r_i,h}$，对$R^{b,r}$右扰动，展开化简，舍去二次小项吗？.

**Comment by thlsealight** [comment]
> 感谢回复，我就用中文了。 所以，这里求导，是整个等式$p^{r_i,h}$，对$R^{b,r}$右扰动，展开化简，舍去二次小项吗？.

对的，扰动舍去二次项，就这个雅克比复杂一些。没有问题我就直接关闭这个issue了。
