### ISSUE TITLE
360度机械雷达

### ISSUE THREAD

**Issue by wolf943134497** [i2Nav-WHU/FF-LINS#10]
您好 请问一下该算法有测试360度机械雷达数据集吗？ 在机械雷达数据集上是否依然精度好于其他算法，谢谢

**Comment by thlsealight** [comment]
> 您好 请问一下该算法有测试360度机械雷达数据集吗？ 在机械雷达数据集上是否依然精度好于其他算法，谢谢

现在已经支持Velodyne和Ouster的LiDAR，精度好坏不是绝对的，不能一概而论。FF-LINS采用帧间数据关联，保证了状态估计的一致性，对大尺度的递推导航而言，FF-LINS具有更好的优势。
