### ISSUE TITLE
Can't find explaination of why frame to map data association resulting in inconsistency in the reference 

### ISSUE THREAD

**Issue by JaySlamer** [i2Nav-WHU/FF-LINS#2]
![Screenshot from 2023-08-30 10-45-00](https://github.com/i2Nav-WHU/FF-LINS/assets/12229227/c0d4b989-f79d-4bd7-ac2c-f9d5a76eee2b)
The reference 10 is VISUAL-INERTIAL NAVIGATION: A CONCISE REVIEW. Within it, I find no explaination. Maybe I somehow missed it. Could you help me by pointing it out.
According to my own understanding, if there is a big difference between the drifts of old and new keyframes, the built local map would be inconsistent, and it is likely the scan to map registration would be unstable or even fail. When we use keyframes that are close in terms of time, there is no such worry. However, we should use GPS and loop closure information to keep drift small anyway. When there is a big drift, inconsistency within local map is not my biggest concern, there is no point to continue the slam anyway. When we build local map using spatial information instead of a simple time window, it provides mid-term and long-term data association that is good to reduce drift.  And slide-window approach introduces too many keyframes into the map its memory footprint grows quickly and unboundedly.  So In my opinion, spatially local map is good for global consistency but bad for local consistency, slide window good for local consistency but bad for global consistency, and the former beats the latter hands-down in memory footprint.

**Comment by JaySlamer** [comment]
我用中文再解释下我的困惑。首先，按这个参考文献我没找到所谓激光雷达帧与地图匹配的不一致的解释，因此我也不知道作者所说的不一致和我认为的不一致是不是一回事。我对scan to map不一致的理解是：局部地图中有一些帧是老的帧，一些帧是新的帧，它们的漂移程度不同，所以不一致。这在我看来不是问题，这些老帧提供中长期数据关联，有利于把最近一帧的飘移减少，而新的帧有利于反映最新的动态变化，不失为一种很好的折中。而滑窗中都是新的帧，自然比较一致，但漂移没有人反应了，就导致问题不能得到解决。打个比方，就好比议会开会，所有人都一致热烈鼓掌，没有任何争吵，这绝不是好事。然而凡事都有个度，如果老帧新帧意见分歧过大，会直接导致点云配准崩坏，好比议会解散内战爆发，也不是好事。解决这个问题绝不是搞一党制（滑窗），把分歧从根源消灭，而是应该不断解决分歧（也就是飘移），避免矛盾积压到爆发。

**Comment by zxd123** [comment]
这里说的不一致指的并不是滑窗里的帧误差的不一致，而是估计得到的协方差与真实误差值的不一致，也就是在里程计中，位姿估计随时间出现了漂移造成误差越来越大，但是协方差(也就是对于当前位姿估计的置信度)并没有随之变大的情况。

**Comment by thlsealight** [comment]
> 这里说的不一致指的并不是滑窗里的帧误差的不一致，而是估计得到的协方差与真实误差值的不一致，也就是在里程计中，位姿估计随时间出现了漂移造成误差越来越大，但是协方差(也就是对于当前位姿估计的置信度)并没有随之变大的情况。

感谢解释，你的解释是我想要表达的意思，这里的不一致就是指的状态估计里面常说的不一致。论文初稿关于不一致这一块描述不够到位，具体等正式版论文。

谢谢！

**Comment by zhh2005757** [comment]
我觉得论文里说的解决这个协方差表达不一致的问题可能主要就是通过滑动窗口图优化框架来解决的。我的理解是这样的：对于一个滑动窗口的状态，利用ceres计算得到的状态协方差和最小二乘计算得到的协方差是类似的，它取决于滑窗中所有约束的权重和残差，其中就包括上一个滑窗遗留下来的边缘化先验残差。换言之，每个滑动窗口的协方差都通过边缘化先验累积到下一个滑窗里，所以最后ceres计算出来的协方差就会逐渐变大。（以上只是我的理解并没有仔细看过代码）

此外，ceres计算的协方差是整个滑窗里最小二乘估计后状态的协方差，然而对于IMU预积分而言，由于是相对两帧的预积分，其协方差是不会因为时间而有明显增长的，因此在做状态估计时，LiDAR和IMU预积分的相对观测权重是基本不怎么变的，这和基于滤波的激光惯性方法是一样的，因而论文中给出协方差自然增长的结果很可能是滑动窗口图优化本身的结构结合先验边缘化因子带来的，而这种协方差的增长并不是状态本身协方差的增长，并不会像传统滤波方法一样，会在激光雷达观测参与优化时自适应改变观测与IMU预测之间的相对权重，而只是将激光惯性里程计作为一个整体的子系统参与GNSS优化时，可以利用该协方差做文章，否则的话整个激光IMU里程计的漂移应该会按照协方差的增长不断增大，而不是像论文中结果反而精度提高了。
