### ISSUE TITLE
A problem about covariance

### ISSUE THREAD

**Issue by zxd123** [i2Nav-WHU/FF-LINS#3]
Thanks for sharing the great work!
But I have a question. In the paper, I saw that the standard deviation of some dimensions increases over time (such as yaw), but when optimizing with ceres, how to get the covariance of the estimated result (or the standard deviation of the corresponding dimension)?
中文：
但是有个疑问想请教一下，在论文中看到了一些维度的标准差在随时间增长(比如yaw的标准差)，但是用ceres进行优化时，是如何得到估计结果的协方差(或对应维度的标准差呢)

**Comment by thlsealight** [comment]
Please refer to [Ceres Solver](http://ceres-solver.org/nnls_covariance.html).
