### ISSUE TITLE
用avia 和 mid360 实测总是不成功。不知道哪里出问题了

### ISSUE THREAD

**Issue by Torchmm** [i2Nav-WHU/FF-LINS#4]
使用avia和mid360时，在fusion.cc中变换IMU坐标系为前右下，同时外参配置里的q配置成（1，0，0，0）.但是运行后，雷达一动就会点云漂移。不知道是否哪里配置错误。
![微信图片_20240105095006](https://github.com/i2Nav-WHU/FF-LINS/assets/46178739/906295c6-9b45-4673-a3d8-78faa5569773)
![85513b8230e3c814c039a9af20467c8](https://github.com/i2Nav-WHU/FF-LINS/assets/46178739/613ce93e-581a-4268-b301-437e610ade08)

**Comment by thlsealight** [comment]
麻烦提供下Fusion::imuCallback的完整实现。

**Comment by Torchmm** [comment]
感谢您的回复！
mid360的IMU时间戳不是很均匀，会有一些红色，avia的IMU时间戳会好一点，但是测试效果都不是很理想。
![1704799255107](https://github.com/i2Nav-WHU/FF-LINS/assets/46178739/38dfc727-334e-4958-9176-5115a9100999)
![1704799269336](https://github.com/i2Nav-WHU/FF-LINS/assets/46178739/6f2ad74d-9769-4283-be7e-14a8beddc153)

**Comment by thlsealight** [comment]
这两款LiDAR我们都测试过没有问题，我稍后更新下IMU数据处理，目前的处理有一些问题。

**Comment by thlsealight** [comment]
代码我已更新，如果开源数据集测试都不存在问题，请检查使用的数据集，我将关闭这个issue。
