### ISSUE TITLE
lixov-avia

### ISSUE THREAD

**Issue by linglingling555** [i2Nav-WHU/FF-LINS#5]
Hello, which LIVOX lidar is the author using, the IMU orientation of the three axes of the 3D map I built after running with livox-avia does not seem to be quite right. Where should I change the configuration file, and what configuration should I change to?

**Comment by thlsealight** [comment]
> Hello, which LIVOX lidar is the author using, the IMU orientation of the three axes of the 3D map I built after running with livox-avia does not seem to be quite right. Where should I change the configuration file, and what configuration should I change to?

Hello, as mentioned in README, the IMU data should be in the front-right-down format in FF-LINS. You can modified the source code or your ROS bag.
